[package]
name = "palladin-inject"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
getrandom.workspace = true
hex.workspace = true
palladin-api = { path = "../palladin-api" }
palladin-browser-bridge = { path = "../palladin-browser-bridge" }
palladin-credential = { path = "../palladin-credential" }
palladin-runtime = { path = "../palladin-runtime" }
secrecy.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
zeroize.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
nix.workspace = true

[dev-dependencies]
serde_json.workspace = true
