d /etc/palladin 0755 root root -
d /etc/palladin/agents.d 0755 root root -
d /var/lib/palladin-runtime 0700 palladin-runtime palladin-runtime -
d /var/lib/palladin-runtime/v1 0700 palladin-runtime palladin-runtime -
